### ISSUE TITLE
Crashed app

### ISSUE THREAD

**Issue by savva643** [SaschaK/TuyaMusicSync#1]
When I added account and restarted app, he started crashing. But if I turn off lamps he will working, where I can get logs?

**Comment by SaschaK** [comment]
Hi, you will find the logs in the Windows Event log

**Comment by firmanraharjo** [comment]
Hi, I actually had the same issue. Once I've added the account, region, access ID and secret, as well as a device ID. It keeps crashing every time I launch the app. The error in the logs I've found are below:

`Application: TuyaCoreController.exe
CoreCLR Version: 6.0.3224.31407
.NET Version: 6.0.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.InvalidDataException: Invalid header/prefix
   at com.clusterrr.TuyaNet.TuyaParser.DecodeResponse(Byte[] data, Byte[] key, TuyaProtocolVersion protocolVersion) in C:\Users\Sasch\Downloads\tuyanet-main\tuyanet-main\TuyaParser.cs:line 132
   at com.clusterrr.TuyaNet.TuyaScanner.UdpListener33Thread(Object o) in C:\Users\Sasch\Downloads\tuyanet-main\tuyanet-main\TuyaScanner.cs:line 119
   at System.Threading.Thread.StartCallback()
`

`Faulting application name: TuyaCoreController.exe, version: 1.0.0.0, time stamp: 0x6377d97d
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3733, time stamp: 0xf527a1c6
Exception code: 0xe0434352
Fault offset: 0x00149a72
Faulting process id: 0x0x6EA0
Faulting application start time: 0x0x1DADC324AD2C33C
Faulting application path: C:\Users\Firman\Downloads\TuyaMusicSync_Executeable-main\TuyaMusicSync_Executeable-main\TuyaCoreController.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 03b7c949-0340-43a3-92e5-27d864949715
Faulting package full name: 
Faulting package-relative application ID: `

Any idea what I can do to fix this? Thanks!
